import { CoveredProject } from '../src/lcov'
import { buildMessage } from '../src/message'

describe('buildMessage', () => {
  it('returns an empty string when projects array is empty', () => {
    const projects = []
    const sha = 'abcdef1234567890'
    const result = buildMessage(projects, sha)
    expect(result).toEqual('')
  })

  const projectA = {
    name: 'project_a',
    description: 'Description A',
    pubspecFile: 'packages/project_a/pubspec.yaml',
    coverage: [],
    coverageBefore: [],
    coverageFile: 'packages/project_a/coverage/lcov.info'
  }

  const projectB = {
    name: 'project_b',
    description: 'Description B',
    pubspecFile: 'packages/project_b/pubspec.yaml',
    coverage: [],
    coverageBefore: [],
    coverageFile: 'packages/project_b/coverage/lcov.info'
  }

  it('returns the correct message when projects array has one project', () => {
    const projects: CoveredProject[] = [projectA]
    const sha = 'abcdef1234567890'
    const result = buildMessage(projects, sha)
    expect(result).toEqual(expected1Project)
  })

  it('returns the correct message when projects array has two projects', () => {
    const projects: CoveredProject[] = [projectA, projectB]
    const sha = 'abcdef1234567890'
    const result = buildMessage(projects, sha)
    expect(result).toEqual(expected2Projects)
  })
})

const expected1Project = `# Coverage Report
This is an automatic coverage report for abcdef12, proudly generated by [Dart Coverage Assistant](https://github.com/whynotmake-it/dart-coverage-assistant) 🎯🧪.

## \`project_a\`
Description A

![0% - fail](http://img.shields.io/badge/project__a-0.00%25-critical)    ➡️ 0.00%


<details>
<summary>Coverage Details for <strong>project_a</strong></summary>

| File | Line Percentage | Line Count |
| --- | --- | --- |

</details>

`

const expected2Projects = `# Coverage Report
This is an automatic coverage report for abcdef12, proudly generated by [Dart Coverage Assistant](https://github.com/whynotmake-it/dart-coverage-assistant) 🎯🧪.

## Monorepo coverage
This repository contains 2 Dart projects. This is is the total coverage across all of them:

![0% - fail](http://img.shields.io/badge/0.00%25-critical)    ➡️ 0.00%

## \`project_a\`
Description A

![0% - fail](http://img.shields.io/badge/project__a-0.00%25-critical)    ➡️ 0.00%


<details>
<summary>Coverage Details for <strong>project_a</strong></summary>

| File | Line Percentage | Line Count |
| --- | --- | --- |

</details>

## \`project_b\`
Description B

![0% - fail](http://img.shields.io/badge/project__b-0.00%25-critical)    ➡️ 0.00%


<details>
<summary>Coverage Details for <strong>project_b</strong></summary>

| File | Line Percentage | Line Count |
| --- | --- | --- |

</details>

`
